module.exports = {
  extends: ['airbnb', 'airbnb/hooks', 'plugin:@typescript-eslint/recommended', 'prettier'],
  overrides: [
    {
      files: ['cypress.config.ts', 'cypress/**/*.ts', '**/*.test.ts'],
      rules: {
        '@typescript-eslint/no-namespace': 0,
        '@typescript-eslint/no-var-requires': 0,
        'global-require': 0,
        'import/no-extraneous-dependencies': [2, { devDependencies: true }],
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'prettier'],
  root: true,
  rules: {
    '@typescript-eslint/lines-between-class-members': 2,
    '@typescript-eslint/no-shadow': 2,
    '@typescript-eslint/no-unused-vars': 2,
    '@typescript-eslint/no-use-before-define': 2,
    '@typescript-eslint/no-useless-constructor': 2,
    'import/extensions': [
      2,
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'import/no-unresolved': [2, { ignore: ['resume'] }],
    'import/order': [2, { alphabetize: { order: 'asc' } }],
    'import/prefer-default-export': 0,
    'no-bitwise': [2, { allow: ['~'] }],
    'no-shadow': 0,
    'no-use-before-define': 0,
    'no-useless-constructor': 0,
    'prettier/prettier': 2,
    'react/function-component-definition': [2, { namedComponents: 'arrow-function' }],
    'react/jsx-filename-extension': [2, { extensions: ['.tsx', '.jsx'] }],
    'react/jsx-sort-props': [2, { shorthandLast: true }],
    'react/no-unescaped-entities': 0,
    'react/prop-types': 0,
    'react/react-in-jsx-scope': 0,
    'react/require-default-props': 0,
    'sort-keys': [2, 'asc', { natural: true }],
  },
  settings: {
    react: {
      version: '18',
    },
  },
};
